### ISSUE TITLE
project gitignore files contain user-specific patterns

### ISSUE THREAD

**Issue by boopcamt** [crowlogic/arb4j#122]
Some .gitignore files in the project seem to match editor-specific temp files. For example, `native/.gitignore` contains the pattern `/arb.i~`

https://git-scm.com/docs/gitignore :

> Which file to place a pattern in depends on how the pattern is meant to be used.
> 
> - Patterns which should be version-controlled and distributed to other repositories via clone (i.e., files that all developers will want to ignore) should go into a .gitignore file.
> 
> - Patterns which are specific to a particular repository but which do not need to be shared with other related repositories (e.g., auxiliary files that live inside the repository but are specific to one user’s workflow) should go into the $GIT_DIR/info/exclude file.
> 
> - Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

Suggestions:

- Reserve project .gitignore files only for stuff that every user should ignore, like build artifacts.
- Keep user-specific patterns in your personal `$HOME/.config/git/ignore`. For instance, match any file that ends in a tilde with this pattern: `*~`

Bonus suggestion: probably only need one .gitignore file for the entire project, easier to keep track of things that way

**Comment by boopcamt** [comment]
sleeping dog

**Comment by crowlogic** [comment]
I was trying to sleep. Some corporate idiots had the audacity to call me
and wake me up, i told em o dont care about no damn citi card stfu
