### ISSUE TITLE
Design  ModuliSpace interface

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#90]

**Comment by RalphSteinhagen** [comment]
@crowlogic could you elaborate a bit more? What is the required feature/application? Thanks in advance.

**Comment by crowlogic** [comment]
the general intent of the interface design is to be able to express the

relations between the related structures, by using Java's generics
support so that the yet-to-be ModularCurve interface can then be
constructed. it needs to be high-performance and allow the flexibility
to be used in the definitions of the other types of things that moduli
spaces can be defined over

From page 8 of [MODULI SPACES OF RIEMANN SURFACES](https://github.com/crowlogic/arb4j/blob/master/src/arb/geometry/doc-files/ModuliSpacesOfRiemannSurfaces.pdf)

2.6. Moduli space. Moduli space Mg is the set of Riemann surfaces
of genus g up to biholomorphism. There is a map Tg → Mg given by
forgetting the marking: (X, φ) 7→ X. Moduli space caries the quotient
topology.
M CG(S) acts on Tg by precomposing the marking φ with the inverse
of the mapping class. Two points (X, φ1 ), (X, φ2 ) that map to the same
point in M CG(S) differ by the action of the mapping class φ−1
2 ◦ φ1 .
Thus, Mg is the quotient of Tg by M CG(S).
Proposition 2.5. If S has genus 1, the action of M CG(S) = SL(2, Z)
on T1 = H is by the usual action of fractional linear transformations
conjugated by z 7→ −z.
In particular, M1 = H/SL(2, Z), which is called the modular curve.
2.6. Moduli space. Moduli space Mg is the set of Riemann surfaces
of genus g up to biholomorphism. There is a map Tg → Mg given by
forgetting the marking: (X, φ) 7→ X. Moduli space caries the quotient
topology.
M CG(S) acts on Tg by precomposing the marking φ with the inverse
of the mapping class. Two points (X, φ1 ), (X, φ2 ) that map to the same
point in M CG(S) differ by the action of the mapping class φ−1
2 ◦ φ1 .
Thus, Mg is the quotient of Tg by M CG(S).
Proposition 2.5. If S has genus 1, the action of M CG(S) = SL(2, Z)
on T1 = H is by the usual action of fractional linear transformations
conjugated by z 7→ −z.
In particular, M1 = H/SL(2, Z), which is called the modular curve.

**Comment by RalphSteinhagen** [comment]
@crowlogic sorry -- mea culpa maxima est -- commented/posted in the wrong repo. :grimacing:

**Comment by crowlogic** [comment]
No worries,  it was a nice exercise to do.  I hope you don't run the accelerators  like you do your github interface ;)
