### ISSUE TITLE
Define Preimage interface

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#91]
https://mathworld.wolfram.com/Preimage.html

**Comment by RalphSteinhagen** [comment]
@crowlogic could you elaborate a bit more? What is the required feature/application? Thanks in advance.

**Comment by crowlogic** [comment]
I imagined this to be more of a [marker interface](https://www.baeldung.com/java-marker-interfaces)

**Comment by RalphSteinhagen** [comment]
@crowlogic sorry -- mea culpa maxima est -- commented/posted in the wrong repo. :grimacing:
